export const SET_ALL_ALBUM_LIST = "SET_ALL_ALBUM_LIST";
export const SET_ALL_USER_LIST = "SET_ALL_USER_LIST";
export const SET_ALBUM_LIST_TOTAL_PAGES = "SET_ALBUM_LIST_TOTAL_PAGES";
export const SET_ALBUM_LIST_CURRENT_PAGE = "SET_ALBUM_LIST_CURRENT_PAGE";

export const SET_ALBUM_ITEM = "SET_ALBUM_ITEM";
export const SET_ALBUM_PHOTOS = "SET_ALBUM_PHOTOS";
export const SET_ALBUM_ITEM_TOTAL_PAGES = "SET_ALBUM_ITEM_TOTAL_PAGES";
export const SET_ALBUM_ITEM_CURRENT_PAGE = "SET_ALBUM_ITEM_CURRENT_PAGE";
